### ISSUE TITLE
ERROR Unable to open "default folder". Folder not found.

### ISSUE THREAD

**Issue by Yaghiyah** [symfony-cmf/cmf-sandbox#302] opened 2015-11-03 08:35 UTC
I keep getting an error using the cmf-sandbox or even just using the cmf bundles on another site why or what is causing this ?? I followed all the instructions.. 
!
![image_browse_error](https://cloud.githubusercontent.com/assets/1174161/10904204/e53a3866-8219-11e5-8a24-29359e6225f9.PNG)

**Comment by dbu** [comment] 2015-11-03 08:47
without more context, it is hard to say. are you sure this is not an error message of your webserver? can you access static files on the domain?

**Comment by Yaghiyah** [comment] 2015-11-03 09:03
I've updated the ticket, the image shows the error I'm receiving 

http://mywebsite.local:8005/efconnect?mode=&cmd=open&target=&init=1&tree=1&_=1446541199771
```javascript
{"error":["errOpen","default folder","errFolderNotFound"],"debug":{"connector":"php","phpver":"5.5.19","time":0.10716104507446,"memory":"19632Kb \/ 19558Kb \/ 128M","upload":"","volumes":[{"id":"p1_","name":"ndle\\mediabundle\\adapter\\elfinder\\phpcrdriver","mimeDetect":"finfo","imgLib":"gd"}],"mountErrors":[]}}
```

**Comment by dbu** [comment] 2015-11-03 09:10
ah, something with the elfinder setup? did you look into http://symfony.com/doc/current/cmf/bundles/media/adapters/elfinder.html#installation ? are you using a 2.x or a 1.x version of the ElfinderBundle?

maybe try configuring the elfinder to use a filesystem adapter and do uploads into the filesystem, to see where the problem is.

**Comment by Yaghiyah** [comment] 2015-11-03 09:15
my cmf media configs looks like this

```javascript
# Cmf Configuration
cmf_core:
    persistence:
        phpcr: true
        # if you want another basepath
        #basepath: /cms
    publish_workflow: false

cmf_media:
    persistence:
        phpcr:
            enabled: true
            manager_name:    ~
            media_basepath:  /cms/media
            media_class:     Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Media
            file_class:      Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\File
            directory_class: Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Directory
            image_class:     Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Image
            event_listeners:
                stream_rewind:    true
                image_dimensions: true
                imagine_cache:    auto


# The media browser elFinder is integrated with Symfony using the FMElfinderBundle.
# The MediaBundle provides an adapter to use it with objects implementing the MediaBundle interfaces.
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: true # defaults to false
                roots:
                      media:
                          driver: cmf_media.adapter.elfinder.phpcr_driver
                          path: %cmf_media.persistence.phpcr.media_basepath%
                          url: http://soundsreal.local:8005/
                          upload_allow: ['all']
                          upload_max_size: 2M

# http://symfony.com/doc/current/cmf/bundles/create/configuration.html
# Security¶
# The controller that receives save requests from create.js does a security check to determine whether the current user is allowed to edit content.
# As it would not be convenient to show the create.js editor to users not allowed to edit the site, the controller loading the create.js JavaScript
# files with the includeJSFilesAction also uses the same security check, as does the image upload controller if it is activated.
# The default security check checks if the user has a specified role. If nothing is configured, the default role is ROLE_ADMIN.
# If you set the parameter to boolean false, every user will be allowed to save changes through the REST controller.
# A last option is to configure your own checker_service to be used instead of the role based check.
cmf_create:
    editor_base_path: /bundles/cmfcreate/vendor/ckeditor/
    security:
        # WARNING: REMOVE THIS FOR PRODUCTION SITES
        # for demo purposes we are allowing anonymous inline editing
        #role: IS_AUTHENTICATED_ANONYMOUSLY
        role: ROLE_ADMIN
```

**Comment by Yaghiyah** [comment] 2015-11-03 09:30
Driver LocalFileSystem only works for me. Why does cmf_media.adapter.elfinder.phpcr_driver
fail ?

```javascript

fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: true # defaults to false
                roots:
                      media:
                          driver: LocalFileSystem
                          path: uploads
                          upload_allow: ['all']
                          upload_max_size: 2M

```
![works](https://cloud.githubusercontent.com/assets/1174161/10904696/de038404-821d-11e5-99a7-1d5eca72e761.png)

**Comment by dbu** [comment] 2015-11-03 09:52
i am not sure how much the phpcr storage is used. maybe there is a bug.
or it was not initialized and the media path in the repository did not
exist.

**Comment by Yaghiyah** [comment] 2015-11-09 09:34
Hi Guys

Did anyone have a chance to look into this? without the fm_elfinder working I cannot delete/browse/ manage file uploads to the phpcr backend this means the system is in limbo.

**Comment by dbu** [comment] 2015-11-09 09:45
in our project we simply use the file storage for media files. i don't expect any of the core contributors to look into this very soon. if you want to dig into it, we are glad to help you figure out what is going on, however.

**Comment by Yaghiyah** [comment] 2015-11-09 09:58
okay, I will use the file system as well, its not a big deal for me, I would suggest updating the sandbox to use the file just for completeness. 

If I get some time I will try and get some insight into what the problem is.

**Comment by puffinofdoom** [comment] 2015-12-13 17:59
Line 294 of https://github.com/helios-ag/ElFinderPHP/blob/master/src/ElFinder.php appears to have a hardcoded namespace which would explain why you cannot override the driver.

**Comment by Aridjar** [comment] 2016-02-25 18:55
I have the same problem, but the solution is not a good one for me (I've to use phpcr).

Did you change/find something which may be related to the problem ?

**Comment by wouterj** [comment] 2016-08-04 13:56
closing as this is not related to the CMF project.

**Closed by wouterj** 2016-08-04 13:56 UTC

**Comment by morwalz** [comment] 2017-05-24 10:05
did anyone found the solution of the problem on windows ?
